// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6I4GvLrRAgBHEuFi4ApjWoO0nszyfeM',
    appId: '1:902133404787:web:7346d656233f58be444606',
    messagingSenderId: '902133404787',
    projectId: 'toko-telyu-ddcef',
    authDomain: 'toko-telyu-ddcef.firebaseapp.com',
    storageBucket: 'toko-telyu-ddcef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB-U2LeHvZHzw1eJEZ9yQ9nWDeOP8KSnY',
    appId: '1:902133404787:android:0f4cfccc5de4c713444606',
    messagingSenderId: '902133404787',
    projectId: 'toko-telyu-ddcef',
    storageBucket: 'toko-telyu-ddcef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxceIogEEwc7s42WGUgSuP1a43CFDLo8g',
    appId: '1:902133404787:ios:4adc4dcc761a2894444606',
    messagingSenderId: '902133404787',
    projectId: 'toko-telyu-ddcef',
    storageBucket: 'toko-telyu-ddcef.firebasestorage.app',
    iosBundleId: 'com.example.tokoTelyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxceIogEEwc7s42WGUgSuP1a43CFDLo8g',
    appId: '1:902133404787:ios:4adc4dcc761a2894444606',
    messagingSenderId: '902133404787',
    projectId: 'toko-telyu-ddcef',
    storageBucket: 'toko-telyu-ddcef.firebasestorage.app',
    iosBundleId: 'com.example.tokoTelyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe6I4GvLrRAgBHEuFi4ApjWoO0nszyfeM',
    appId: '1:902133404787:web:6b3d2951df8dde79444606',
    messagingSenderId: '902133404787',
    projectId: 'toko-telyu-ddcef',
    authDomain: 'toko-telyu-ddcef.firebaseapp.com',
    storageBucket: 'toko-telyu-ddcef.firebasestorage.app',
  );
}
